project:
  type: website
  output-dir: _site

website:
  title: "Contelia"
  description: "Boîte à histoires"
  favicon: favicon.ico

  announcement: 
    content: "Ce site est en cours de construction"
    position: below-navbar
    dismissable: false

  navbar:
    logo: images/contelia-256.png
    left:
      - href: project/manual.qmd
        text: Prise en main
      - href: project/kit.qmd
        text: Kit de montage
      - href: project/downloads.qmd
        text: Téléchargements
    right:
      - icon: github
        href: https://github.com/Skywalker13/contelia

  page-footer:
    left: "© 2025-2026 Mathieu Schroeter"
    center: "Ce site est hébergé par un Raspberry Pi 4 fonctionnant sous Carnotzet OS"

  search: true

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    link-external-icon: true
    link-external-newwindow: true

  pdf:
    author: Mathieu Schroeter
    documentclass: article
    classoption: [12pt, a4paper]
    geometry:
      - top=3cm
      - bottom=2cm
      - left=3cm
      - right=2cm
    fontfamily: libertinus
    colorlinks: true
    toc: true
    number-sections: true
    include-in-header:
      text: |
        \usepackage{microtype}
        \usepackage{booktabs}
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{}
        \fancyhead[L]{\leftmark}
        \fancyfoot[L]{https://contelia.schroetersa.ch}
        \fancyfoot[R]{\thepage}
        \renewcommand{\headrulewidth}{0pt}

lang: fr