---
title: "Téléchargements"
subtitle: "Ressources pour Contelia"
lang: fr-CH
abstract: Une utilisation normal de Contelia ne nécessite pas de téléchargement
  particulier. Mais si vous avez l'âme d'un bidouilleur, ici vous trouverez
  toutes les ressources nécessaires pour ré-imaginer votre propre boîte à
  histoires; voir même en faire un nouveau projet complètement différent.
---

## Pour les bidouilleurs

La boîte à histoire contient une carte micro-SD préinstallée et qui peut être
changée ou réinstallée avec une nouvelle version de Contelia OS, voir même
votre propre OS (si vous avez l'âme d'un [hacker]).

Pour accéder à la carte micro-SD, il est nécessaire de démonter partiellement
la boîte à histoire en suivant [la procédure suivante][1].

### Images de Contelia OS

_Contelia OS_ : [contelia-os-1.0.0.zip][2] (NON DISPONIBLE)

L'installation doit se faire comme expliqué avec [le kit de montage][3]. En
quelques mots, vous allez utiliser le logiciel balenaEtcher pour déployer
l'image décompressée de Contelia OS sur la carte micro-SD. Il est important de
se référer complètement au kit de montage jusqu'à ce que la boîte soit remontée
proprement.

## Pour les développeurs et les makers

### Le code source

Le logiciel principal de Contelia est disponible sur [GitHub][4]. Il est écrit
en Rust sous licence libre GPLv3+.

### Les modèles 3D

Tous les modèles 3D sont disponibles dans le même dépôt de code-source que le
logiciel. Ils ont été entièrement réalisé à l'aide de [FreeCAD] et suivent la
même licence que le code source.

### Le toolchain de compilation

Le toolchain de compilation se nomme Xcraft et permet de créer la distribution
Linux Contelia OS. Cet OS est basé sur Carnotzet OS qui est un système
d'exploitation GNU/Linux entièrement construit pour ce projet (ainsi que pour
des projets annexes). Le système de base se nomme [Carnotzet OS][5].

Xcraft est un projet vaste et complexe. Compiler Contelia OS de zéro est tout
a fait possible pour n'importe qui, qui est alaise avec les outils de
développement et les concepts sous-jacents comme le packaging, la
compilation croisée, etc.

[METTRE A DISPO UNE PROCEDURE PAS A PAS POUR CONTELIA OS]

[1]: sd.html
[2]: /downloads/contelia-os-1.0.0.zip
[3]: kit.html#préparation
[4]: https://github.com/Skywalker13/contelia
[FreeCAD]: https://www.freecad.org/
[5]: https://xcraft.ch/carnotzet/index.html
[hacker]: https://fr.wikipedia.org/wiki/Hacker_(sous-culture)