---
title: "Des histoires"
subtitle: "Charger des histoires dans Contelia"
lang: fr
---

## Des histoires

La boîte à histoire ne sert à rien sans contenu. Mais le contenu n'est bien
souvent pas disponible gratuitement. Mais en cherchant bien, il existe
quelques projets communautaires et de plus, si vous avez déjà une boîte à
histoires Lunii, il est possible de les charger sur Contelia (attention, cela
ne concerne pas la Flam).

Contelia ne contient aucune histoire de base, et c'est à vous d'en charger.
Mais tout d'abord, où en trouver ?

### Lunii

Récupérer les histoires que vous avez acheté avec la Lunii fait sens. Pour celà
il faut brancher la Lunii à votre ordinateur, un nouveau périphérique devrait
s'afficher en tant que disque USB.

TODO

Vous trouverez une liste de dossiers avec des noms cryptiques. Ce sont les
histoires. Copier tous les dossiers sur le disque de votre ordinateur. Puis
pour chaque dossier, créez un fichier ZIP. Ce sont ces fichiers ZIP qui pourront
être chargé dans Contelia.

### Communautaire

Il existe des packs d'histoires disponibles gratuitement dans une communauté
francophone que vous pouvez rejoindre par l'intermédiaire du
logiciel Discord : https://monurl.ca/lunii.creations. Cette communauté met à
dispositions de nombreux livres, donne des conseils, de l'aide et sert
également de vitrine pour de nombreux autres projets qui partage le même esprit
que Contelia, c'est à dire d'offrir des alternatives aux boîtes à histoires
Lunii, etc. Que ce soit du matériel dédié ou du "recyclage" de smartphones en
liseuses pour enfants.

Vous y trouverez également toute l'aide nécessaire pour pouvoir créer vos
propres histoires si le coeur vous en dis.